### PR TITLE
bugfix: error when rpc playlist add netease song

### PR DESCRIPTION
**Pull request by SaneBow**
This should fix this issue: https://github.com/feeluown/FeelUOwn/issues/491

### CODE REVIEW

**Comment by SaneBow** [comment]
好像不是这个问题，先关闭我再研究下

**Comment by SaneBow** [comment]
又测试了一遍应该是可以修复，开发者看下这个修复对不对吧

**Comment by cosven** [comment]
LGTM.
Moreover, can you please add a unittest to cover this case?

**Comment by SaneBow** [comment]
Not sure how to do that. Would you help to add the unit test?

**Comment by cosven** [comment]
> Not sure how to do that. Would you help to add the unit test?

OK, I will submit a PR.

**Pull request merged**
