### PR TITLE
Renamed __cache__ to _cache

### PR DESCRIPTION
**Pull request by Torxed**
This would fix https://github.com/feeluown/FeelUOwn/issues/715 in the sense that it builds against pydantic >= 2.

I'm trying to package it for https://archlinux.org/packages/extra/any/feeluown/ and this PR should address the packaging issue at least.

*Small note: I signed with my packager key, but used my github email, hence "Unverified"*

### CODE REVIEW

**Review by cosven — APPROVED** [review]
LGTM

You may also need to update setup.py.
https://github.com/feeluown/FeelUOwn/blob/35ae8144828cd5c5b83b8ea6881da77eb8c55753/setup.py#L60

**Comment by Torxed** [comment]
Done, just note that I haven't done extensive testing with it.
I only verified that it builds against pydantic 2.0.3 and that the application launches.

**Comment by cosven** [comment]
I'll take a look at the unit tests and try to fix them.

**Comment by Torxed** [comment]
Thank you. We do run `pytest` in our build script https://gitlab.archlinux.org/archlinux/packaging/packages/feeluown/-/blob/6de55acb5b84104c4e40d1888c310470fa4ce4f2/PKGBUILD - but for the other tests, perhaps https://pypi.org/project/bump-pydantic/ can be of use?

**Comment by cosven** [comment]
> We do run `pytest` in our build script https://gitlab.archlinux.org/archlinux/packaging/packages/feeluown/-/blob/6de55acb5b84104c4e40d1888c310470fa4ce4f2/PKGBUILD 

That's great. With this commit https://github.com/feeluown/FeelUOwn/pull/718/commits/73ceab1661c526bc117c7087e2b007b1e537dedd, all test cases should pass.

> but for the other tests, perhaps https://pypi.org/project/bump-pydantic/ can be of use?

Thanks, this tip helps a lot.

**Pull request merged**
